### ISSUE TITLE
AES解密那里报错

### ISSUE THREAD

**Issue by zhengwangeng** [nosqlcoco/springboot-weapp-demo#1]
` AES aes = new AES();
            byte[] resultByte = aes.decrypt(encryptedData.getBytes(), Base64.decodeBase64(sessionKey), iv.getBytes());
            if(null != resultByte && resultByte.length > 0){
                String userInfo = new String(resultByte, "UTF-8");
                System.out.println(userInfo);
            }`

这里执行会报错，错误信息：java.security.NoSuchProviderException: No such provider: PKCS#7
我用的是JDK.1.8.20, 并使用jce_policy-8.zip修改了JDK下的策略文件（local_policy.jar，US_export_policy.jar）

**Comment by cocoli** [comment]
已解决；
AES类中把Cipher cipher = Cipher.getInstance("AES/EBC/PKCS7Padding","PKCS#7");
改成为Cipher cipher = Cipher.getInstance("AES/CBC/PKCS7Padding");

**Comment by zhengwangeng** [comment]
按照您的代码修改（改成为Cipher cipher = Cipher.getInstance("AES/CBC/PKCS7Padding");），出现新的问题：
`
java.security.spec.InvalidParameterSpecException: IV not 16 bytes long
	at com.sun.crypto.provider.BlockCipherParamsCore.init(BlockCipherParamsCore.java:63)
	at com.sun.crypto.provider.AESParameters.engineInit(AESParameters.java:54)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:275)
	at com.weapp.common.aes.AES.generateIV(AES.java:61)
	at com.weapp.common.aes.AES.decrypt(AES.java:30)
	at com.weapp.AESTest.main(AESTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
`

以下为完整测试代码：
`
package com.weapp;

import com.weapp.common.aes.AES;
import org.apache.commons.codec.binary.Base64;

import java.io.UnsupportedEncodingException;
import java.security.InvalidAlgorithmParameterException;

/**
 * 。</br>
 * Created by zhengwangeng on 16/11/24.
 */
public class AESTest {
    public static void main(String[] args) {
        //String sessionKey = "PWGZy5rhCxC2kD7qWdcLnQ==";
        //String encryptedData = "zKTqrQdzh2CD/QmleuC0v/8oqzuZrRjoVCsWUMCYOEzPq+LC/YTUFGCcy5kfj9ThO2IGNoBfuzyMa/PF32CgrZOmSHaSs1K4PIx/RhrUjHr75WAd5xvtRKF5zSNvUIagV1P4RqyM69f1HzgOtNSj7iXIPqwfF0e8QIc5RhpdAjKjKnpK8ceGM6GkGpgRtWcxe/kNIgg92zvuL9cmembcOukCEnZGgU0+PF4QO5vriABBsWW9taY9b6ix+ZjPMeeojoi4dg2glwChyfozEZSK7Rgzhmt8A8j6Xtd+tdKBn9aNw/1qhuVEukLYbfdrAoDY1q9REhftokmxaZI9fAci3AwzMEsnau2wnLkGBgrByruKo4T9fOzMtBKgxgWntkesa8yj8D1cu34qMcKH9v+kbXJc2sLQ7RXl9FmcKwpcMo45GWyFlD74FA+UmLq9EjXc";
        //String iv = "AgHT70uCy5ToBxQZfjCnXg==";

        String sessionKey = "bvVygdLqvNPUGyx8hzHoBg==";
        String encryptedData = "yAiThwP1W/AVf9CmBFCyepfaFMRjJAFjZTLEbO6OJxmDoAKa0JO7ooP2pYP9ZqXYeEqCNoHfnXqCLNfSPQQbGDejBQaa5DTJx4qIZFKT6uxLaqtVOZXO2UmP15Nb6Lskb/QF1TiIDrdL/NF+Fe74zQmRrkG/cSP+kcegYnUfLmYZ14xWvknUON8ELO886gp1ntQu8JWzFeuJxpLFa+o1u3rbZanlz5XqxgelJIjfGN6TpYK6kzcZy/7wcmKm/zrk9Y4OiaQYw1aqKaciAMNLg6kWVk8bElgGRT4wyfQABNJ0vDL5w96UkRgViuaM9OvOzBAzYZWeTY0xcyJNIsPhCSx9lLXa9iHa6X76z+oaSNGk0G9Mwl9Ekhg3dqdhb6OGYJcnB4SsBa9xTs61rBkc6dcVKf9MJ9JuMOh01fXeacDCnfuKqXHmaARzscC55ba1";
        String iv = "NA5iIh+BU/ShhTOP7XvUPQ==";


        try {
            AES aes = new AES();
            byte[] resultByte = aes.decrypt(encryptedData.getBytes(), Base64.decodeBase64(sessionKey), iv.getBytes());

            if(null != resultByte && resultByte.length > 0){
                String userInfo = new String(resultByte, "UTF-8");
                System.out.println(userInfo);
            }
        } catch (InvalidAlgorithmParameterException e) {
            e.printStackTrace();
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }
}

`

**Comment by cocoli** [comment]
您的测试代码中：aes.decrypt(encryptedData.getBytes(), Base64.decodeBase64(sessionKey), iv.getBytes());
iv向量使用Base64.decodeBase64(iv)解编码

**Comment by zhengwangeng** [comment]
使用 iv向量使用Base64.decodeBase64(iv)解编码 会出现下面的异常：
`
javax.crypto.BadPaddingException: pad block corrupted
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2121)
	at com.weapp.common.aes.AES.decrypt(AES.java:31)
	at com.weapp.AESTest.main(AESTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
`

**Comment by dark3212** [comment]
我也碰到了javax.crypto.BadPaddingException: pad block corrupted
at org.bouncycastle.jce.provider.JCEBlockCipher.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
而且是时好时坏，有时候能解密出来，有时候就报错

**Comment by nosqlcoco** [comment]
我怀疑是微信官方加密的问题，有许多同学反应一样的情况，暂时无法解决你遇到的解密失败问题。
